inherit_from:
  - config/style_guides/ruby.yml
  - .rubocop_todo.yml

# Files you want to exclude
AllCops:
  Exclude:
    - bin/*
    - db/**/*
    - tasks/*
    - lib/tasks/*
    - Gemfile
    - Rakefile
    - bundle/**/*
